%% matlab_run_validation_set.m
% Runs the full 12-config validation set by calling matlab_capture_validation_batch
% once per config. Total clock time: ~30-60 minutes unattended on a modern laptop.
%
% Prereq: `addpath(genpath(pwd))` so IndPenSim_V2.02/ and scripts/ are both visible.
%
% Each config gets a unique seed; Python test reads the same seed list.

configs = {
    struct('seed', 101, 'faults', 0, 'raman', 0, 'fixed', 1, 'tag', 'vanilla_a'), ...
    struct('seed', 102, 'faults', 0, 'raman', 0, 'fixed', 1, 'tag', 'vanilla_b'), ...
    struct('seed', 103, 'faults', 0, 'raman', 0, 'fixed', 1, 'tag', 'vanilla_c'), ...
    struct('seed', 201, 'faults', 1, 'raman', 0, 'fixed', 1, 'tag', 'fault_aeration'), ...
    struct('seed', 202, 'faults', 2, 'raman', 0, 'fixed', 1, 'tag', 'fault_pressure'), ...
    struct('seed', 203, 'faults', 3, 'raman', 0, 'fixed', 1, 'tag', 'fault_substrate'), ...
    struct('seed', 204, 'faults', 4, 'raman', 0, 'fixed', 1, 'tag', 'fault_base'), ...
    struct('seed', 205, 'faults', 5, 'raman', 0, 'fixed', 1, 'tag', 'fault_coolant'), ...
    struct('seed', 207, 'faults', 7, 'raman', 0, 'fixed', 1, 'tag', 'fault_Tsensor'), ...
    struct('seed', 208, 'faults', 8, 'raman', 0, 'fixed', 1, 'tag', 'fault_pHsensor'), ...
    struct('seed', 301, 'faults', 0, 'raman', 2, 'fixed', 1, 'tag', 'raman_paa_loop'), ...
    struct('seed', 401, 'faults', 0, 'raman', 0, 'fixed', 0, 'tag', 'variable_length')
};

start_time = tic;
for i = 1:numel(configs)
    c = configs{i};
    fprintf('[%2d/%2d] %s  (seed=%d faults=%d raman=%d fixed=%d)\n', ...
            i, numel(configs), c.tag, c.seed, c.faults, c.raman, c.fixed);
    seed_label            = c.seed;
    faults_override       = c.faults;
    raman_override        = c.raman;
    fixed_length_override = c.fixed;
    matlab_capture_validation_batch;
end
fprintf('=== DONE. Total elapsed: %.1f min ===\n', toc(start_time)/60);
